default: &default
  adapter: mysql2
  pool: 20
  timeout: 5000
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: portfolio_development
  username: portfolio
  password: portfolio
  host: localhost
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: portfolio_test
  username: portfolio
  password: portfolio
  host: localhost

production:
  <<: *default
  database: portfolio_production
  username: portfolio
  password: hyde0129lec
  host: localhost
  port: 3306
